language: python
env:
    - TOXENV=py27-django18
    - TOXENV=py34-django18
    - TOXENV=py35-django18
    - TOXENV=py27-django19
    - TOXENV=py34-django19
    - TOXENV=py35-django19
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libgeoip-dev
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
